# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RZ-R0LlKihk-DhAjUoU4RNUeKnbVl_iQ
"""

!pip install hmmlearn

from hmmlearn.hmm import CategoricalHMM
import numpy as np

# Model
model = CategoricalHMM(n_components=3)

# Example parameters (you can adjust)
model.startprob_ = np.array([0.3, 0.4, 0.3])
model.transmat_ = np.array([
    [0.7, 0.2, 0.1],
    [0.3, 0.4, 0.3],
    [0.2, 0.3, 0.5]
])
model.emissionprob_ = np.array([
    [0.8, 0.2],  # Interested
    [0.5, 0.5],  # Neutral
    [0.2, 0.8]   # Disengaged
])

# Observations (0=click, 1=no-click)
observations = np.array([[0], [1], [1], [0]])

# Predict hidden states
hidden_states = model.predict(observations)

print("Predicted Hidden States:", hidden_states)

